name: Manual Tests

on:
  workflow_dispatch:
    inputs:
      test_case:
        description: 'Choose the test case to run'
        required: true
        default: 'full'
        type: choice
        options:
          - full
          - print_not_in_given_data_symbols
          - print_not_listed_symbols

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install selenium pytest pytest-xdist
          
      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip

          # Install Google Chrome
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb

          # Verify Google Chrome installation and fetch version
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
          echo "Google Chrome version: $CHROME_VERSION"

      - name: Install Compatible ChromeDriver
        run: |
          # Determine the ChromeDriver URL for the installed Chrome version
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
          echo "Google Chrome version: $CHROME_VERSION"
          CHROMEDRIVER_URL="https://storage.googleapis.com/chrome-for-testing-public/${CHROME_VERSION}/linux64/chromedriver-linux64.zip"
          echo "ChromeDriver URL: $CHROMEDRIVER_URL"

          # Download and install ChromeDriver
          wget $CHROMEDRIVER_URL
          unzip chromedriver-linux64.zip
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver

          # Verify ChromeDriver installation
          chromedriver --version

      - name: Run Tests
        run: |
          export CHROME_HEADLESS="--headless --no-sandbox --disable-dev-shm-usage"
          
          if [ "${{ github.event.inputs.test_case }}" = "full" ]; then
            pytest -v -s 
          elif [ "${{ github.event.inputs.test_case }}" = "print_not_in_given_data_symbols" ]; then
            pytest -v -s -k test_print_not_in_given_data_symbols
          elif [ "${{ github.event.inputs.test_case }}" = "print_not_listed_symbols" ]; then
            pytest -v -s -k test_print_not_listed_symbols
          fi
